ui:
  title: WF Status
  header: Wayfinder Blame Dashboard
  description: 'Days since last incident: 398'
  logo: >-
    https://pbs.twimg.com/profile_images/1768421252450934784/eEJYGxvM_400x400.jpg
alerting:
  slack:
    webhook-url: >-
      https://hooks.slack.com/services/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
endpoints:
  - name: Wayfinder Login
    group: api-health
    url: https://app.wayfinder.ai
    conditions:
      - '[STATUS] == 200'
      - '[RESPONSE_TIME] < 2000'
    alerts:
      - type: slack
        failure-threshold: 5
        description: Wayfinder NextJS is down
        send-on-resolved: true
    interval: 10s
  - name: Wayfinder Django
    group: api-health
    url: >-
      https://app.wayfinder.ai/api/v1/chat_ai_proxy/abi/?contract_address=0xef4fb24ad0916217251f553c0596f8edc630eb66&chain_name=base
    conditions:
      - '[STATUS] == 200'
      - '[RESPONSE_TIME] < 2000'
    alerts:
      - type: slack
        failure-threshold: 5
        description: Wayfinder Django is down
        send-on-resolved: true
    interval: 10s
